export const FILE_TYPES = {
  PDF_FILES: ["pdf"],
  DOCUMENTS: ["doc", "docx", "txt", "rtf", "odt", "ods", "odp"],
  SPREADSHEETS: ["xls", "xlsx", "csv"],
  TEXT_FILES: ["txt", "rtf", "xml"],
  PRESENTATIONS: ["ppt", "pptx", "key"],
  ARCHIVES: ["zip", "rar", "7z", "tar", "gz"],
  PASSWORD_FILES: [
    "pwd",
    "passwd",
    "shadow",
    "htpasswd",
    "wp-config",
    "kdbx",
    "cred",
    "secrets",
    "keychain",
    "pfx",
  ],
  LOGIN_FILES: [
    "login",
    "logon",
    "auth",
    "session",
    "token",
    "cookies",
    "signin",
    "cert",
    "jwt",
    "oauth",
  ],
  DATABASE_FILES: [
    "db",
    "sql",
    "sqlite",
    "mdb",
    "accdb",
    "frm",
    "ibd",
    "myd",
    "ndf",
    "ora",
  ],
  LOG_FILES: [
    "log",
    "csv",
    "json",
    "xml",
    "audit",
    "trace",
    "debug",
    "out",
    "err",
  ],
  CONFIG_FILES: [
    "cfg",
    "ini",
    "conf",
    "xml",
    "json",
    "yml",
    "toml",
    "env",
    "cnf",
    "properties",
  ],
  BACKUP_FILES: ["bak", "backup", "tar", "old", "bkp", "arc"],
};
